export const MOTIVATION_QUOTES = [
  "One focused study session can change the direction of your whole day.",
  "Progress becomes visible when you keep showing up for small tasks.",
  "A difficult chapter becomes easier when you start with one clear question.",
  "Study a little today so tomorrow feels less rushed.",
  "Your next solved problem is waiting for your next focused minute.",
  "Consistency turns ordinary study sessions into strong results.",
  "Do the next useful thing, even when the full task feels large.",
  "A page understood deeply is more valuable than ten pages rushed.",
  "Practice gives your knowledge somewhere to go when the exam begins.",
  "Small improvements repeated often become a powerful advantage.",
  "You do not need a perfect session; you need a real one.",
  "Start with the easiest question and let momentum build from there.",
  "Every revision makes familiar ideas easier to recall under pressure.",
  "A mistake can point directly to the concept that needs another look.",
  "Focused effort for twenty minutes is still meaningful progress.",
  "Keep learning even when the results are not visible yet.",
  "The goal is not to know everything; it is to understand something better today.",
  "A calm mind remembers more when the preparation has been steady.",
  "One honest attempt teaches more than avoiding a difficult question.",
  "Read carefully, think clearly, and let understanding take the lead.",
  "Your study routine becomes stronger every time you protect it from distraction.",
  "Do not measure the whole journey by one difficult lesson.",
  "Hard topics become manageable when you break them into smaller parts.",
  "The best time to review a weak concept is before it becomes a repeated mistake.",
  "Your notebook can become a map of everything you have learned.",
  "A solved example is a step between confusion and confidence.",
  "Keep asking why; curiosity often opens the door that memorization cannot.",
  "You learn faster when you test what you think you know.",
  "A short review today can save a long struggle later.",
  "Protect your attention like it is part of your study material.",
  "One distraction avoided is one more useful thought completed.",
  "Learning is built from questions, attempts, corrections, and another try.",
  "Do not wait for motivation to begin; let beginning create momentum.",
  "A steady pace is easier to maintain than a last-minute rush.",
  "When a lesson feels heavy, reduce the size of the next step.",
  "Your future revision becomes easier when you understand the idea now.",
  "A quiet study session can produce progress that nobody else can see yet.",
  "Keep going through the boring parts; mastery often lives there.",
  "One formula understood properly can unlock many questions.",
  "The questions you struggle with can become the questions that teach you most.",
  "Your effort counts even when today only adds one small improvement.",
  "Reviewing your mistakes is a study session, not a failure report.",
  "A clear plan reduces the noise around difficult work.",
  "Make the next question easier by understanding the previous one.",
  "Your attention is limited, so spend it where it helps you learn.",
  "Knowledge grows quietly, then becomes obvious when you need it.",
  "Keep your standards high and your next step small.",
  "A difficult subject becomes less intimidating with regular contact.",
  "Study for understanding first; speed can come later.",
  "The habit of checking your answer can prevent the habit of repeating errors.",
  "A few focused pages can be enough to move a topic forward.",
  "When you feel stuck, write down what you already know.",
  "Your next breakthrough may start with a very simple example.",
  "Strong preparation is usually the result of many ordinary days.",
  "Keep a little space for curiosity alongside your deadlines.",
  "Every time you explain an idea in your own words, you strengthen it.",
  "A question mark can be the beginning of a much better understanding.",
  "Do not confuse slow progress with no progress.",
  "Rest can support learning when it helps you return with a clearer mind.",
  "Good study is less about hours and more about useful attention.",
  "Make difficult material smaller until the next step feels possible.",
  "The chapter does not need to be easy for you to keep moving.",
  "One focused hour can create several easier hours later.",
  "Your mistakes are useful when you turn them into specific lessons.",
  "Repetition becomes powerful when each review asks you to recall, not just reread.",
  "A strong study day can begin with one phone-free session.",
  "Confidence grows naturally when your preparation gives it evidence.",
  "You are allowed to learn slowly; you are not required to learn carelessly.",
  "A clean desk is optional; a clear next step is not.",
  "When the task feels boring, remember that skill is built by repetition.",
  "Do one problem carefully before doing ten problems quickly.",
  "Your notes become more useful every time you organize what confused you.",
  "A focused question can be more productive than an unfocused hour.",
  "Keep practicing the skill that your last test revealed.",
  "The first attempt does not need to be your best attempt.",
  "A good revision session turns weak memory into familiar knowledge.",
  "When you cannot see the finish line, focus on the next page.",
  "Study with patience; difficult ideas often make sense after enough contact.",
  "A consistent routine leaves less room for panic later.",
  "Every definition you understand becomes a tool for harder questions.",
  "Do not let one wrong answer decide what you are capable of learning.",
  "A little discipline today can create a calmer tomorrow.",
  "The best shortcut is often understanding the concept properly.",
  "Your learning gets stronger when you can solve without looking at the answer.",
  "Use difficult questions as practice for staying calm and thinking clearly.",
  "A chapter is easier to remember when you connect it to something you already know.",
  "One more example can sometimes turn a vague idea into a clear one.",
  "Keep your study sessions realistic enough to repeat tomorrow.",
  "A focused learner is built through habits, not perfect moods.",
  "The more clearly you identify a gap, the easier it is to close it.",
  "Review, recall, apply, and repeat; learning grows through use.",
  "Your effort today can reduce the pressure you feel next week.",
  "You do not need to finish everything to make meaningful progress.",
  "Start where you are, use what you know, and improve one step at a time.",
  "A strong answer often begins with a careful reading of the question.",
  "Practice makes your thinking more automatic when time is limited.",
  "Protect a few minutes every day for the topics you avoid.",
  "The subject may be difficult, but the next step can still be simple.",
  "Every useful summary saves future study time.",
  "One well-made flashcard can become a reliable memory cue.",
  "When you teach an idea, you discover what you truly understand.",
  "A calm correction today is better than repeating the same mistake tomorrow.",
  "Your study progress is allowed to look different from someone else’s.",
  "Keep comparing yourself to your own last attempt, not somebody else’s timeline.",
  "A small streak of focused days can rebuild a forgotten habit.",
  "The answer becomes easier to trust when you know how you reached it.",
  "Learning gets stronger when you turn passive reading into active recall.",
  "Your next revision can begin with the one topic you remember least.",
  "A clear example can teach more than a long explanation without practice.",
  "Do not rush past confusion; investigate it.",
  "Your brain benefits from returning to important ideas more than once.",
  "One finished task can create enough momentum for the next one.",
  "Difficult work feels lighter when your plan tells you exactly what to do next.",
  "Keep your goals visible and your daily actions specific.",
  "A study habit becomes easier when you attach it to a regular time.",
  "The notes you improve today can become your best revision tool later.",
  "Every solved problem adds another pattern to your mental toolbox.",
  "You can be tired and still choose a small, useful step.",
  "A quiet five-minute review can keep an important idea alive.",
  "The purpose of practice is not perfection; it is better performance through feedback.",
  "When you get an answer wrong, ask what thought led you there.",
  "Your progress is often hiding inside habits that look ordinary.",
  "One focused block can be more valuable than a whole evening of scattered study.",
  "Make your study session easy to start and hard to interrupt.",
  "A better question can lead to a better understanding.",
  "Keep your difficult topics close enough that they stop feeling unfamiliar.",
  "A concept becomes useful when you can recognize it in a new problem.",
  "The next revision is another chance to turn recall into confidence.",
  "Do not wait for the perfect environment; create a workable one.",
  "Your study plan should help you begin, not overwhelm you.",
  "Each correction gives your next attempt a better starting point.",
  "When a task feels huge, choose one page, one problem, or one definition.",
  "Patience is a study skill too.",
  "The work you repeat carefully becomes the skill you trust later.",
  "Keep reading for meaning, not just for completion.",
  "A good question bank is useful only when you learn from the answers.",
  "One accurate diagram can make a complicated process much easier to remember.",
  "The best revision sessions include retrieval, not just recognition.",
  "Your future self benefits from the notes you make carefully today.",
  "Do not let a slow chapter make you forget how much you already understand.",
  "A focused start can make an uncertain study day feel more manageable.",
  "You can improve a weak area without making it your whole identity.",
  "One extra practice question can reveal a gap before an exam does.",
  "The more you practice thinking, the less you depend on remembering exact wording.",
  "A useful study session leaves you knowing what changed.",
  "Keep asking for clarity when a concept does not make sense yet.",
  "A difficult question deserves another attempt, not an immediate conclusion.",
  "Every time you return to a concept, you give your memory another path to it.",
  "Do not count only completed chapters; count the concepts you truly understand.",
  "Learning is easier when your study environment supports the goal.",
  "A small amount of daily practice can beat occasional bursts of effort.",
  "The habit of starting is one of the most useful habits a student can build.",
  "Strong preparation makes exam questions look more familiar.",
  "Keep your focus on the work in front of you.",
  "Your next good decision can be as simple as opening the book.",
  "A concept that feels obvious now was once something you did not know.",
  "Use feedback as information about your method, not your worth.",
  "One revision cycle can change how confident a topic feels.",
  "When memory fades, revisit; forgetting is a signal to practice again.",
  "Good learners make room for both effort and rest.",
  "Your study rhythm matters more than one unusually productive day.",
  "A well-understood mistake can prevent several future mistakes.",
  "Do not fear difficult questions; let them show you where to grow.",
  "Every completed practice set makes the next set easier to approach.",
  "The best notes are the ones you can actually use later.",
  "Take the pressure off perfection and put the attention on the next action.",
  "Your concentration improves when you decide in advance what matters most.",
  "One chapter finished with understanding is a solid step forward.",
  "Keep building your foundation; advanced topics become easier on strong basics.",
  "A simple checklist can turn a vague plan into visible progress.",
  "When you solve a problem, explain why the method works.",
  "A little curiosity can make a routine lesson much more interesting.",
  "Your questions are evidence that you are engaging with the material.",
  "Stay with the concept until you can explain it without copying the textbook.",
  "Every review is an opportunity to notice what has become easier.",
  "A focused learner does not avoid mistakes; they use them efficiently.",
  "Your preparation can be quiet and still be powerful.",
  "Keep your daily target small enough that you can meet it consistently.",
  "A clear understanding is worth more than a fast but fragile memory.",
  "You can restart your study routine today without waiting for a new week.",
  "The next ten minutes can be useful even when the next ten hours are uncertain.",
  "When motivation is low, reduce the task before you reduce the goal.",
  "One careful read can save several confused rereads.",
  "Keep practicing the questions that make you think instead of only the ones you already know.",
  "A strong student is still learning how to learn.",
  "Every focused session adds evidence that you can rely on your habits.",
  "The effort that feels repetitive today can feel effortless later.",
  "A calm review before sleep can help important ideas stay active.",
  "Use your strongest study method on your weakest topic.",
  "When you finish a task, record what you learned from doing it.",
  "Your next improvement may come from changing your method, not increasing your hours.",
  "One good habit can support many academic goals at once.",
  "The value of studying is not only the grade; it is the ability you build.",
  "Keep your attention on what you can improve today.",
  "A difficult concept becomes less mysterious each time you work through an example.",
  "You are building recall every time you answer before checking the solution.",
  "Use short breaks to reset attention, not to lose the whole study session.",
  "A steady learner can recover from a weak day without abandoning the routine.",
  "Keep the next step obvious, and starting becomes easier.",
  "One more explanation from a different angle may unlock the idea.",
  "The best preparation includes enough practice to make mistakes before the real test.",
  "Every question you review is another chance to strengthen your reasoning.",
  "Do not underestimate what repeated small sessions can accomplish.",
  "Your notebook can hold questions, answers, corrections, and progress all in one place.",
  "A focused morning can set the tone for the rest of your study day.",
  "When a lesson feels complicated, find the simplest part first.",
  "Keep returning to the basics whenever advanced material starts to feel unclear.",
  "One useful sentence in your notes can trigger an entire concept later.",
  "The habit of checking sources and steps makes your work more reliable.",
  "Your strongest improvement may begin with one honest look at what you do not know.",
  "A completed review is one less unknown waiting for exam day.",
  "Good study habits reduce decisions, leaving more energy for learning.",
  "Practice makes confidence more dependable because it gives confidence evidence.",
  "When you explain a difficult topic simply, you know you are getting somewhere.",
  "Your daily effort does not need to impress anyone to be valuable.",
  "Choose progress that you can repeat.",
  "One question understood deeply can be the key to many similar questions.",
  "Your study routine is built one start at a time.",
  "Keep moving through difficult material without demanding instant understanding.",
  "Every careful correction makes the next attempt more informed.",
  "A strong study session leaves fewer things unclear than when it began.",
  "The next page can be the page where a difficult idea finally connects.",
  "Build your preparation before you need it.",
  "A little review now can make recall feel natural later.",
  "Focus on accuracy first, then work on speed.",
  "Your learning improves when you notice patterns, not just answers.",
  "A consistent routine gives difficult subjects more chances to become familiar.",
  "Do not postpone the topic simply because it is uncomfortable.",
  "One focused block today is a vote for a calmer tomorrow.",
  "Keep your study tools simple enough that they help instead of distracting.",
  "The effort you make to understand one concept can support an entire chapter.",
  "When you finish a study session, leave yourself a clear starting point for the next one.",
  "Every day offers another chance to strengthen a skill.",
  "Your progress can be quiet, gradual, and still very real.",
  "A learner becomes stronger by staying curious after the first answer.",
  "One more attempt can reveal a method you did not see before.",
  "Keep learning through uncertainty; clarity often arrives after several attempts.",
  "The work you do before the deadline is easier to trust than hope at the deadline.",
  "A smart study session has a clear target and a simple next step.",
  "Do not abandon a useful habit because one day went badly.",
  "Your best revision tool is often the mistake you understood properly.",
  "Every chapter connects to something else; look for the relationship.",
  "One focused question can restart an entire study session.",
  "Keep practicing until the process feels familiar, then keep practicing accurately.",
  "A steady learner gives hard topics enough time to become understandable.",
  "You do not need to feel ready to take the next step.",
  "Use today to make tomorrow's study a little easier.",
  "A small improvement is still an improvement worth keeping.",
  "The more you retrieve information, the stronger the pathway back to it becomes.",
  "Keep your study goals clear and your distractions expensive.",
  "One completed task can turn a stressful evening into a productive one.",
  "Your understanding grows when you connect new ideas with old ones.",
  "Do not rush past the part that teaches you why the answer works.",
  "A focused learner gives attention before asking for results.",
  "Keep your routine flexible enough to survive busy days.",
  "The purpose of revision is to make important knowledge easier to access.",
  "One honest practice session can reveal more than a page of passive reading.",
  "Your next achievement may be hidden inside today's smallest task.",
  "Keep building skills that remain useful after the exam is over.",
  "When a topic feels impossible, make the question smaller.",
  "A consistent review schedule gives memory many chances to strengthen.",
  "You can improve without rushing and finish without burning out.",
  "One solved example can become a pattern you recognize again and again.",
  "Keep your attention on what you are learning, not only on how much remains.",
  "A better study day can begin with a simple decision to start.",
  "Use mistakes to adjust your method while the lesson is still fresh.",
  "Your progress is built from ordinary choices repeated with care.",
  "One chapter at a time is still the whole syllabus eventually.",
  "Let curiosity keep you engaged when discipline feels heavy.",
  "The more clearly you know your weak areas, the more efficiently you can practice.",
  "A calm approach can improve both learning and recall.",
  "Keep your study sessions focused enough that you know what you accomplished.",
  "Small wins create useful momentum when you notice and repeat them.",
  "A difficult problem can train patience as well as knowledge.",
  "Every review session is a chance to make future recall faster.",
  "Your notes should answer the questions you are likely to forget.",
  "Practice a little beyond comfort so unfamiliar questions feel less unfamiliar later.",
  "The quality of one focused session can matter more than the length of a distracted one.",
  "Keep your learning active by predicting, solving, explaining, and checking.",
  "A strong foundation is built through details taken seriously.",
  "Do not wait for confidence; build it through preparation.",
  "One useful habit today can remove several problems later.",
  "Your study journey can move forward even after a difficult week.",
  "Return to the idea that confused you and see what is clearer now.",
  "A patient learner gives understanding time to develop.",
  "Every answer you explain becomes easier to reproduce under pressure.",
  "Keep the routine simple, the goal clear, and the next task visible.",
  "One focused session is enough to change the next decision you make.",
  "Your preparation grows every time you practice before you feel completely ready.",
  "A difficult subject becomes familiar through regular, deliberate effort.",
  "Keep going with the question in front of you.",
  "You can always make the next study step smaller.",
  "Every concept you master gives you more room to tackle the next one.",
  "A useful revision note can save time when pressure is high.",
  "The habit of starting quickly can protect your best attention.",
  "Do not let one bad score hide the lessons inside it.",
  "Your method can improve even when the material stays challenging.",
  "One more practice round can turn a weak skill into a familiar one.",
  "Keep your effort steady enough that progress has somewhere to accumulate.",
  "Learning is a process of making difficult things more familiar.",
  "Your next review can be the one that makes the concept stick.",
  "A clear question often makes a difficult topic easier to attack.",
  "Do the important work before the pressure makes it urgent.",
  "Small steps are useful because they are easier to repeat.",
  "Keep your attention on the process that creates improvement.",
  "One careful attempt is a better starting point than endless hesitation.",
  "When you practice with feedback, every error can become useful information.",
  "A learner who keeps returning to the basics can handle harder material with more ease.",
  "Your study effort becomes stronger when your plan matches your real day.",
  "A calm ten-minute session is better than waiting for a perfect hour.",
  "Keep exploring the part that makes you curious.",
  "Your progress deserves patience while your habits become stronger.",
  "One lesson learned well can make the next lesson easier to enter.",
  "Study with enough focus that your time leaves something behind.",
  "The best study routine is one you can return to consistently.",
  "A difficult question is a chance to practice both knowledge and reasoning.",
  "Keep your standards clear and your self-judgment quiet.",
  "Every page you understand adds to a foundation nobody can take from you.",
  "One small task can reopen momentum after a distracted day.",
  "Your future exam performance is shaped by the practice you choose now.",
  "Review the things you tend to forget before they become emergencies.",
  "A focused learner turns time into practice instead of just counting hours.",
  "Your best progress may come from repeating a simple method well.",
  "Keep asking better questions and your understanding will keep growing.",
  "One more minute of attention can be the difference between guessing and understanding.",
  "A consistent learner gives every important concept more than one chance.",
  "Use today to strengthen one thing you want to trust later.",
  "Your study session does not have to be perfect to be productive.",
  "When you feel behind, start with the most useful next step.",
  "Small consistent effort can make a large syllabus feel less intimidating.",
  "Keep the lessons that mistakes teach you.",
  "A strong memory is built through repeated retrieval, not hope.",
  "One solved question can become the first of many.",
  "Your learning becomes more durable when you use it in different ways.",
  "Keep preparing before confidence feels necessary.",
  "A thoughtful pause can sometimes improve an answer more than rushing.",
  "The next study session is another chance to improve your method.",
  "Every focused day adds another layer to your preparation.",
  "Do not measure progress only by speed; measure it by understanding.",
  "A clear routine makes it easier to protect your study time.",
  "Keep working until the confusing part becomes explainable.",
  "Your next small action can be enough to restart the habit.",
  "Practice turns unfamiliar tasks into recognizable patterns.",
  "One careful review can be worth more than several rushed rereads.",
  "Let your questions guide your revision.",
  "You can make progress without making every session long.",
  "A well-timed review gives important ideas another chance to stay.",
  "Keep learning in a way that leaves room for curiosity and rest.",
  "Your preparation becomes stronger when you face weak areas directly.",
  "One useful example can unlock the idea behind many exercises.",
  "The work may be repetitive, but the skill you build is not.",
  "Keep your next action specific enough that you can begin immediately.",
  "A learner who checks their reasoning learns more from each answer.",
  "Your daily practice can be small and still change your level over time.",
  "Difficult lessons reward patience, repetition, and good questions.",
  "One focused session can make the next session easier to start.",
  "Keep your learning moving even when your pace changes.",
  "The best evidence of progress is being able to do something you could not do before.",
  "A strong revision habit makes important ideas easier to retrieve.",
  "Your study time matters when your attention is actually present.",
  "One solved problem can teach a method, not just an answer.",
  "Keep improving the process and the results can follow.",
  "A difficult topic deserves patience instead of avoidance.",
  "Your next question may reveal the connection you were missing.",
  "The effort you repeat becomes the ability you can rely on.",
  "Keep the routine alive with a task small enough to finish.",
  "A good study session should leave you with more clarity than confusion.",
  "Your academic growth is built through many ordinary moments of attention.",
  "One more review can make a familiar idea easier to use.",
  "When the syllabus feels large, work on the next useful piece.",
  "Keep practicing the skill, not just reading about it.",
  "A calm learner can think more clearly when questions become difficult.",
  "Your next step can be simple even when your long-term goal is ambitious.",
  "Every useful correction strengthens the next attempt.",
  "The habit of finishing small tasks creates confidence in larger ones.",
  "Keep your study method honest enough to show what you really remember.",
  "A question you cannot answer yet is an invitation to learn.",
  "Your progress becomes easier to trust when you can explain it to yourself.",
  "One clear target can protect an entire study session from distraction.",
  "Keep building your skills before you need to prove them.",
  "A strong study routine grows through repetition, adjustment, and patience.",
  "Your next revision is another opportunity to make learning easier for your future self.",
  "One small improvement today can become a much bigger difference after many days.",
  "Keep going; the next clear idea may be closer than it feels.",
] as const;

export const MOTIVATION_QUOTE_COUNT = MOTIVATION_QUOTES.length;
