/**
 * Shared TypeScript types for the College Portal module.
 * Mirrors supabase/migrations/20260710120000_college_portal.sql.
 *
 * These are hand-written rather than pulled from `Database` in
 * src/lib/supabase/database.types.ts because that file is generated by
 * `npm run db:generate-types` — regenerate it after running the migration
 * and these types will start overlapping (that's expected; feel free to
 * replace these with `Database['public']['Tables']['colleges']['Row']`
 * etc. once regenerated).
 */

export type CollegeJoinStatus = "pending" | "approved" | "declined";

export type CollegeResourceType = "notes" | "past_paper" | "slides" | "other";

export interface College {
  id: string;
  name: string;
  slug: string;
  city: string | null;
  logo_url: string | null;
  cover_url: string | null;
  description: string | null;
  is_active: boolean;
  created_by: string | null;
  created_at: string;
}

/** Safe subset of `College` shown to anonymous/public visitors. */
export type PublicCollege = Pick<
  College,
  "id" | "name" | "slug" | "city" | "logo_url" | "cover_url" | "description" | "is_active"
>;

export interface CollegeWithCounts extends PublicCollege {
  lecture_count: number;
  resource_count: number;
}

export interface CollegeWithAdmin extends College {
  admin: { id: string; full_name: string | null; email: string | null } | null;
}

export interface CollegeAdmin {
  id: string;
  college_id: string;
  profile_id: string;
  assigned_by: string | null;
  created_at: string;
}

export interface CollegeJoinRequest {
  id: string;
  student_id: string;
  college_id: string;
  status: CollegeJoinStatus;
  requested_at: string;
  resolved_at: string | null;
  resolved_by: string | null;
}

export interface CollegeJoinRequestWithStudent extends CollegeJoinRequest {
  student: {
    id: string;
    full_name: string | null;
    email: string | null;
    avatar_url: string | null;
  } | null;
}

export interface CollegeLecture {
  id: string;
  college_id: string;
  uploaded_by: string;
  title: string;
  description: string | null;
  course_name: string | null;
  semester: string | null;
  video_url: string;
  created_at: string;
}

export interface CollegeResource {
  id: string;
  college_id: string;
  uploaded_by: string;
  title: string;
  resource_type: CollegeResourceType;
  course_name: string | null;
  semester: string | null;
  file_url: string;
  created_at: string;
}

/** The current student's relationship to the College Portal (sidebar / browse grid). */
export type StudentCollegeState =
  | { state: "none" }
  | { state: "pending"; collegeId: string; collegeName: string; requestId: string }
  | { state: "approved"; collegeId: string; collegeName: string; collegeSlug: string };

export interface ActionResult<T = undefined> {
  success: boolean;
  error?: string;
  data?: T;
}
