import { createElement } from 'react';
import { renderToStaticMarkup } from 'react-dom/server';
import QRCode from 'react-qr-code';
import sharp from 'sharp';
import { describe, expect, it } from 'vitest';
import { decodeQrImage } from './qr-server';

describe('server parent QR decoder', () => {
  it('reads the same SVG QR format generated by the parent dashboard', async () => {
    const payload = 'https://ilmai.study/parent-link?code=SV-A1B2C3';
    const svg = renderToStaticMarkup(createElement(QRCode, { value: payload, size: 360, level: 'M' }));
    const screenshot = await sharp(Buffer.from(svg)).png().toBuffer();

    await expect(decodeQrImage(screenshot)).resolves.toBe(payload);
  }, 15_000);
});
