/**
 * Phase 6b — server-side report card PDF, built from school_report_cards.summary (the same
 * per-subject breakdown publishExamResults() already computes — see school-erp/actions.ts) rather
 * than re-deriving marks from school_exam_marks. jsPDF's core text/line drawing API works fine in
 * a Node runtime with no DOM (unlike exportPresentationPdf.ts's html2canvas approach, which is
 * browser-only), so this stays a plain server-side function callable from an API route.
 */

type ReportCardSubject = { subject: string; maxMarks: number; marks: number | null; absent: boolean };

export type ReportCardPdfInput = {
  organizationName: string;
  studentName: string;
  className: string | null;
  examName: string;
  term: string | null;
  totalMarks: number;
  obtainedMarks: number;
  percentage: number;
  grade: string | null;
  gpa: number | null;
  classPosition: number | null;
  teacherComment: string | null;
  aiComment: string | null;
  subjects: ReportCardSubject[];
};

export async function generateReportCardPdf(input: ReportCardPdfInput): Promise<Buffer> {
  const { jsPDF } = await import('jspdf');
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const pageWidth = doc.internal.pageSize.getWidth();
  const margin = 48;
  let y = margin;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(18);
  doc.text(input.organizationName, pageWidth / 2, y, { align: 'center' });
  y += 22;
  doc.setFontSize(13);
  doc.text('Report Card', pageWidth / 2, y, { align: 'center' });
  y += 16;
  doc.setFont('helvetica', 'normal');
  doc.setFontSize(10);
  doc.text(`${input.examName}${input.term ? ` (${input.term})` : ''}`, pageWidth / 2, y, { align: 'center' });
  y += 28;

  doc.setDrawColor(200);
  doc.line(margin, y, pageWidth - margin, y);
  y += 20;

  doc.setFontSize(11);
  doc.text(`Student: ${input.studentName}`, margin, y);
  if (input.className) doc.text(`Class: ${input.className}`, pageWidth - margin, y, { align: 'right' });
  y += 24;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(10);
  doc.text('Subject', margin, y);
  doc.text('Max Marks', margin + 260, y);
  doc.text('Obtained', margin + 360, y);
  y += 6;
  doc.setDrawColor(220);
  doc.line(margin, y, pageWidth - margin, y);
  y += 16;

  doc.setFont('helvetica', 'normal');
  for (const subject of input.subjects) {
    doc.text(subject.subject || 'Subject', margin, y);
    doc.text(String(subject.maxMarks), margin + 260, y);
    doc.text(subject.absent ? 'Absent' : String(subject.marks ?? '-'), margin + 360, y);
    y += 18;
    if (y > 720) {
      doc.addPage();
      y = margin;
    }
  }

  y += 10;
  doc.setDrawColor(200);
  doc.line(margin, y, pageWidth - margin, y);
  y += 22;

  doc.setFont('helvetica', 'bold');
  doc.setFontSize(11);
  doc.text(`Total: ${input.obtainedMarks} / ${input.totalMarks} (${input.percentage}%)`, margin, y);
  y += 18;
  doc.text(`Grade: ${input.grade || '-'}   GPA: ${input.gpa ?? '-'}   Class Position: ${input.classPosition ?? '-'}`, margin, y);
  y += 28;

  if (input.teacherComment) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.text('Teacher comment:', margin, y);
    y += 14;
    doc.setFont('helvetica', 'normal');
    const lines = doc.splitTextToSize(input.teacherComment, pageWidth - margin * 2);
    doc.text(lines, margin, y);
    y += lines.length * 14 + 10;
  }

  if (input.aiComment) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(10);
    doc.text('Additional notes:', margin, y);
    y += 14;
    doc.setFont('helvetica', 'normal');
    const lines = doc.splitTextToSize(input.aiComment, pageWidth - margin * 2);
    doc.text(lines, margin, y);
  }

  doc.setFontSize(8);
  doc.setTextColor(150);
  doc.text('Generated by ilm AI', pageWidth / 2, doc.internal.pageSize.getHeight() - 24, { align: 'center' });

  return Buffer.from(doc.output('arraybuffer'));
}
